### ISSUE TITLE
Implement downloading all texts

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/mymickiewicz-data-preprocessing#2]
## Description

Implement downloading all avaialable Mickiewicz's texts in to the `.txt` format.

\*It turns out (at least in the case of Mickiewicz) that all of the content that's **not** available to download in `.txt`, is in fact just it's `children` concatenated. So, texts that have `children` should simply be ignored (this also eliminates the issue of having to convert between formats).

## TODO

- [ ] Check if `texts` folder exists (if not, create it and skip checks)
- [ ] Get book's `slug`s
- [ ] Check if a file for each `slug` exists in the `texts` folder (if not, perform those requests)
- [ ] Check each details page
  - [ ] If `children` is empty
  - [ ] If `language` isn't Polish
- [ ] Get `.txt` download URLs (first check if it exsists)
- [ ] Download the needed `.txt` files

\*Add execution time meter
\*Log requests with errors (status codes, etc.)

## Resources

- [API](https://wolnelektury.pl/api/)
  - `https://wolnelektury.pl/api/authors/adam-mickiewicz/books/`
  - `https://wolnelektury.pl/api/books/<slug>/`
- Requests
  - `res` -> `response`
  - [5 Ways to Make HTTP Requests in Node.js](https://www.twilio.com/blog/http-requests-in-node-js-html)
  - [Using `then()` vs Async/Await in JavaScript](https://dev.to/masteringjs/using-then-vs-async-await-in-javascript-2pma)
  - [How to download a file with Node.js (without using third-party libraries)?](https://stackoverflow.com/questions/11944932/how-to-download-a-file-with-node-js-without-using-third-party-libraries)
- Multithreading
  - [`thread.js`](https://threads.js.org/usage-pool)
  - [Worker threads](https://nodejs.org/api/worker_threads.html)
  - [Node.js multithreading: Worker threads and why they matter](https://blog.logrocket.com/node-js-multithreading-worker-threads-why-they-matter/)
- Progress bar
  - [`tqdm`](https://github.com/kotborealis/tqdm)
  - [`cli-progress`](https://www.npmjs.com/package/cli-progress)
  - [Python node progress reporting question](https://forum.knime.com/t/python-node-progress-reporting-question/34925)
  - [Applying progress bar library with logger library in nodejs](https://stackoverflow.com/questions/71219470/applying-progress-bar-library-with-logger-library-in-nodejs)
