### ISSUE TITLE
Implement processing steps

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/mymickiewicz-data-preprocessing#3]
## Description

Implement processing steps to make the clean up the texts for training.

## TODO

- [ ] Clean up
  - [ ] Top info (`^(.*?)(?<=\n{4})\n*` - single line mode)
  - [ ] Bottom info (`(\n*)-----.*$` - single line mode)
  - [ ] Uncommon characters (but leave some, like: `…` cause it's one char instead of 3 so more optimal?)
```python
default_chars = "aąbcćdeęfghijklłmnńoópqrsśtuvwxyzźż!?,."

# Get text from file:
f = open("concat.txt", "r") # (just every text concated - `cat $(ls) >> concat.txt`)
text = f.read()
 
# Get every character:
chars = set()

# Splitting text in to chars and putting them in a set (cause of uniqueness)
for char in text.lower().split():
    chars.update(char)

# Removing common chars:
for char in default_chars:
    chars.remove(char)

for char in chars:
    print(char)
```
- [ ] Fix formatting
  - [ ] New lines
  - [ ] Line width
  - [ ] Indentation

- [ ] Others (check manually)

- [ ] Concatenate the files

## Resources

- [tinyshakespeare](https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt)

- [Jest](https://jestjs.io/)
- [regex101](https://regex101.com/)
