### ISSUE TITLE
Finish up `README.md`

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/mymickiewicz-data-preprocessing#4]
## TODO

- [ ] Add TOC\*
- [ ] Add `installation` / `usage` commands
- [ ] Add a gist / pastebin etc. URL to the final `.txt` file (WITH PROPER LICENSE)
- [ ] Add notes
  - [ ] Removing the `texts` folder to 'remove cache' (get new data)
  - [ ] How it's not meant to be a general tool, so there won't be any support for issues and such
  - [ ] How it can be used for getting other author's works BUT it's still kind of a delicate process and it most likely won't produce the best results (regex and so on)
